apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    tier: {{ .Values.tier }}
data:
  poppichu.application.port: {{ .Values.poppichuApplicationPort | quote }}
  tier: {{ .Values.tier }}